/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "(leave empty for Autodiscovery)": {             "en": "(leave empty for Autodiscovery)",                 "de": "(lass es leer für Autodiscovery)",                "ru": "(оставить пустым для автопоиска)",                "pt": "(deixe em branco para descoberta automática)",    "nl": "(leeg laten voor Autodiscovery)",                 "fr": "(laisser vide pour la découverte automatique)",   "it": "(lascia vuoto per il rilevamento automatico)",    "es": "(déjelo vacío para el descubrimiento automático)", "pl": "(pozostaw puste dla automatycznego wykrywania)",  "zh-cn": "（为自动发现留空）"},
    "(select for VIS compatibility)": {              "en": "Check this for VIS compatibility",                "de": "(F&uuml;r VIS Kompatibilität anhaken!)",          "ru": "Проверьте это на совместимость с VIS",            "pt": "Verifique isto para compatibilidade com VIS",     "nl": "Controleer dit op VIS-compatibiliteit",           "fr": "Vérifiez ceci pour la compatibilité VIS",         "it": "Controlla questo per la compatibilità VIS",       "es": "Compruebe esto para la compatibilidad con VIS",   "pl": "Sprawdź to pod kątem zgodności z VIS",            "zh-cn": "检查 VIS 兼容性"},
    "AVR EISCP Port": {                              "en": "AVR EISCP Port",                                  "de": "AVR EISCP Port",                                  "ru": "AVR EISCP порт",                                  "pt": "Porta AVR EISCP",                                 "nl": "AVR EISCP-poort",                                 "fr": "Port EISCP de l'AVR",                             "it": "Porta EISCP AVR",                                 "es": "Puerto AVR EISCP",                                "pl": "Port AVR EISCP",                                  "zh-cn": "AVR EISCP 端口"},
    "Max Volume Zone1": {                            "en": "Max volume of zone1",                             "de": "Maximale Lautst&auml;rke Zone1",                  "ru": "Максимальный объем зоны 1",                       "pt": "Volume máximo da zona 1",                         "nl": "Max volume van zone1",                            "fr": "Volume max de la zone1",                          "it": "Volume massimo della zona1",                      "es": "Volumen máximo de zone1",                         "pl": "Maksymalna objętość strefy1",                     "zh-cn": "zone1 的最大体积"},
    "Max Volume Zone2": {                            "en": "Max volume of zone2",                             "de": "Maximale Lautst&auml;rke Zone2",                  "ru": "Максимальный объем зоны 2",                       "pt": "Volume máximo da zona 2",                         "nl": "Maximaal volume van zone2",                       "fr": "Volume max de la zone2",                          "it": "Volume massimo della zona2",                      "es": "Volumen máximo de zone2",                         "pl": "Maksymalna objętość strefy2",                     "zh-cn": "zone2 的最大体积"},
    "ONKYO adapter settings": {                      "en": "ONKYO adapter settings",                          "de": "ONKYO Einstellungen",                             "ru": "ONKYO Настройки",                                 "pt": "Configurações do adaptador ONKYO",                "nl": "ONKYO-adapterinstellingen",                       "fr": "Paramètres de l'adaptateur ONKYO",                "it": "Impostazioni dell'adattatore ONKYO",              "es": "Configuración del adaptador ONKYO",               "pl": "Ustawienia adaptera ONKYO",                       "zh-cn": "ONKYO 适配器设置"},
    "Onkyo AVR Address": {                           "en": "Onkyo AVR Address",                               "de": "Onkyo AVR Adresse",                               "ru": "Onkyo AVR Адрес",                                 "pt": "Endereço Onkyo AVR",                              "nl": "Onkyo AVR-adres",                                 "fr": "Adresse AVR Onkyo",                               "it": "Indirizzo Onkyo AVR",                             "es": "Dirección de Onkyo AVR",                          "pl": "Adres Onkyo AVR",                                 "zh-cn": "Onkyo AVR 地址"},
};